### ISSUE TITLE
بهبودهای مورد نیاز

### ISSUE THREAD

**Issue by MahdiEsrafili** [HRSadeghi/AI_Internship#1]
- [x]  قسمت Joint، فصل اول: تمرین برای PCA
- [x] قسمت Joint، فصل اول: تمرین برای الگوریتم های پیشرفته تر مانند درخت تصمیم، Random Forrest، XGBoost
- [x] قسمت Joint، فصل اول: ارزیابی و مقایسه مدل ها بر روی یک مسئله و داده ی خاص
- [x] قسمت NLP، فصل P6: تمرین بیشتر برای مدل زبانی (مانند پیش بینی احتمال جملات، پیش بینی کلمه بعدی، ارزیابی مدل)
- [x] قسمت NLP، فصل P8: با کتابخانه های پرکاربرد مانند NLTK، Hazm, Spacy, Stanford Stanza, PolyGlot، تسک هایی مانند NER و POS , Dependency Parsing انجام دهند
- [x] قسمت NLP، فصل P9: تمرین بیشتر مانند طبقه بندی متن یا NER، تمرین برای زبان فارسی
- [x] قسمت NLP، فصل P11: تمرین بیشتر، دیتاست و آموزش برای زبان فارسی
- [x] قسمت NLP، فصل P12: روش هایی ابتدایی و کلاسیک گفته بشه
- [x] ایشوها Issues، بصورت خودکار نمایش داده نمی شود.
- [x] ایشوها کاملا مطابق با توضیحات و تمرین ها نیست (برای مثال در فصل اول P1، تمرین انسمبل داده نشده ولی در ایشوها موجود است)

**Comment by HRSadeghi** [comment]
All the aforementioned items are corrected!

**Comment by MahdiEsrafili** [comment]
تشکر
